version: '3'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:

      - "8087:80"  # Access WordPress on localhost:8080
      
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: kzr
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - net1

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: kzr
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net1

volumes:
  wordpress_data:
  db_data:


networks:
  net1:
  
